# Workflow for building and deploying documentation to GitHub Pages
name: Build and deploy docs

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Clone VulpesCloud Repository
        run: |
          git clone https://github.com/VulpesCloud/VulpesCloud vulpescloud
          cd vulpescloud

      - name: Set up JDK 21
        uses: actions/setup-java@v4.5.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Make Gradle wrapper executable
        run: |
          cd vulpescloud
          chmod +x gradlew

      - name: Build Documentation with Gradle
        run: |
          cd vulpescloud
          ./gradlew dokkaHtmlMultiModule
      - name: Verify Output Directory
        run: |
          cd vulpescloud
          ls -R build/dokka || echo "Directory not found"

  deploy:
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload Documentation Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'vulpescloud/build/dokka/htmlMultiModule'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
